name: Dart Tests CI

on:
  push:
    branches: [ test-branch ]
  pull_request:
    branches: [ dev-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: pub run test
